/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSupportRouteRouteImport } from './routes/_authenticated/support/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVpsIndexRouteImport } from './routes/_authenticated/vps/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedDomainIndexRouteImport } from './routes/_authenticated/domain/index'
import { Route as AuthenticatedDatabaseIndexRouteImport } from './routes/_authenticated/database/index'
import { Route as AuthenticatedContainersIndexRouteImport } from './routes/_authenticated/containers/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai/index'
import { Route as AuthenticatedAffiliateIndexRouteImport } from './routes/_authenticated/affiliate/index'
import { Route as AuthenticatedVpsCreateRouteImport } from './routes/_authenticated/vps/create'
import { Route as AuthenticatedVpsVpsIdRouteImport } from './routes/_authenticated/vps/$vpsId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDomainCreateRouteImport } from './routes/_authenticated/domain/create'
import { Route as AuthenticatedDomainDomainIdRouteImport } from './routes/_authenticated/domain/$domainId'
import { Route as AuthenticatedDatabaseCreateRouteImport } from './routes/_authenticated/database/create'
import { Route as AuthenticatedDatabaseDatabaseIdRouteImport } from './routes/_authenticated/database/$databaseId'
import { Route as AuthenticatedContainersCreateRouteImport } from './routes/_authenticated/containers/create'
import { Route as AuthenticatedContainersContainerIdRouteImport } from './routes/_authenticated/containers/$containerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRouteRoute =
  AuthenticatedSupportRouteRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVpsIndexRoute = AuthenticatedVpsIndexRouteImport.update({
  id: '/vps/',
  path: '/vps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDomainIndexRoute =
  AuthenticatedDomainIndexRouteImport.update({
    id: '/domain/',
    path: '/domain/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseIndexRoute =
  AuthenticatedDatabaseIndexRouteImport.update({
    id: '/database/',
    path: '/database/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContainersIndexRoute =
  AuthenticatedContainersIndexRouteImport.update({
    id: '/containers/',
    path: '/containers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateIndexRoute =
  AuthenticatedAffiliateIndexRouteImport.update({
    id: '/affiliate/',
    path: '/affiliate/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVpsCreateRoute = AuthenticatedVpsCreateRouteImport.update({
  id: '/vps/create',
  path: '/vps/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVpsVpsIdRoute = AuthenticatedVpsVpsIdRouteImport.update({
  id: '/vps/$vpsId',
  path: '/vps/$vpsId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainCreateRoute =
  AuthenticatedDomainCreateRouteImport.update({
    id: '/domain/create',
    path: '/domain/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainDomainIdRoute =
  AuthenticatedDomainDomainIdRouteImport.update({
    id: '/domain/$domainId',
    path: '/domain/$domainId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseCreateRoute =
  AuthenticatedDatabaseCreateRouteImport.update({
    id: '/database/create',
    path: '/database/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseDatabaseIdRoute =
  AuthenticatedDatabaseDatabaseIdRouteImport.update({
    id: '/database/$databaseId',
    path: '/database/$databaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContainersCreateRoute =
  AuthenticatedContainersCreateRouteImport.update({
    id: '/containers/create',
    path: '/containers/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContainersContainerIdRoute =
  AuthenticatedContainersContainerIdRouteImport.update({
    id: '/containers/$containerId',
    path: '/containers/$containerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/support': typeof AuthenticatedSupportRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/containers/$containerId': typeof AuthenticatedContainersContainerIdRoute
  '/containers/create': typeof AuthenticatedContainersCreateRoute
  '/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdRoute
  '/database/create': typeof AuthenticatedDatabaseCreateRoute
  '/domain/$domainId': typeof AuthenticatedDomainDomainIdRoute
  '/domain/create': typeof AuthenticatedDomainCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/vps/create': typeof AuthenticatedVpsCreateRoute
  '/affiliate': typeof AuthenticatedAffiliateIndexRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/containers': typeof AuthenticatedContainersIndexRoute
  '/database': typeof AuthenticatedDatabaseIndexRoute
  '/domain': typeof AuthenticatedDomainIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/vps': typeof AuthenticatedVpsIndexRoute
}
export interface FileRoutesByTo {
  '/support': typeof AuthenticatedSupportRouteRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/containers/$containerId': typeof AuthenticatedContainersContainerIdRoute
  '/containers/create': typeof AuthenticatedContainersCreateRoute
  '/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdRoute
  '/database/create': typeof AuthenticatedDatabaseCreateRoute
  '/domain/$domainId': typeof AuthenticatedDomainDomainIdRoute
  '/domain/create': typeof AuthenticatedDomainCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/vps/create': typeof AuthenticatedVpsCreateRoute
  '/affiliate': typeof AuthenticatedAffiliateIndexRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/containers': typeof AuthenticatedContainersIndexRoute
  '/database': typeof AuthenticatedDatabaseIndexRoute
  '/domain': typeof AuthenticatedDomainIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/vps': typeof AuthenticatedVpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/support': typeof AuthenticatedSupportRouteRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/containers/$containerId': typeof AuthenticatedContainersContainerIdRoute
  '/_authenticated/containers/create': typeof AuthenticatedContainersCreateRoute
  '/_authenticated/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdRoute
  '/_authenticated/database/create': typeof AuthenticatedDatabaseCreateRoute
  '/_authenticated/domain/$domainId': typeof AuthenticatedDomainDomainIdRoute
  '/_authenticated/domain/create': typeof AuthenticatedDomainCreateRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/_authenticated/vps/create': typeof AuthenticatedVpsCreateRoute
  '/_authenticated/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/containers/': typeof AuthenticatedContainersIndexRoute
  '/_authenticated/database/': typeof AuthenticatedDatabaseIndexRoute
  '/_authenticated/domain/': typeof AuthenticatedDomainIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/vps/': typeof AuthenticatedVpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/callback'
    | '/'
    | '/containers/$containerId'
    | '/containers/create'
    | '/database/$databaseId'
    | '/database/create'
    | '/domain/$domainId'
    | '/domain/create'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/vps/$vpsId'
    | '/vps/create'
    | '/affiliate'
    | '/ai'
    | '/billing'
    | '/containers'
    | '/database'
    | '/domain'
    | '/settings/'
    | '/vps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/callback'
    | '/'
    | '/containers/$containerId'
    | '/containers/create'
    | '/database/$databaseId'
    | '/database/create'
    | '/domain/$domainId'
    | '/domain/create'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/vps/$vpsId'
    | '/vps/create'
    | '/affiliate'
    | '/ai'
    | '/billing'
    | '/containers'
    | '/database'
    | '/domain'
    | '/settings'
    | '/vps'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/containers/$containerId'
    | '/_authenticated/containers/create'
    | '/_authenticated/database/$databaseId'
    | '/_authenticated/database/create'
    | '/_authenticated/domain/$domainId'
    | '/_authenticated/domain/create'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/vps/$vpsId'
    | '/_authenticated/vps/create'
    | '/_authenticated/affiliate/'
    | '/_authenticated/ai/'
    | '/_authenticated/billing/'
    | '/_authenticated/containers/'
    | '/_authenticated/database/'
    | '/_authenticated/domain/'
    | '/_authenticated/settings/'
    | '/_authenticated/vps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps/': {
      id: '/_authenticated/vps/'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof AuthenticatedVpsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/domain/': {
      id: '/_authenticated/domain/'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof AuthenticatedDomainIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database/': {
      id: '/_authenticated/database/'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers/': {
      id: '/_authenticated/containers/'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AuthenticatedContainersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate/': {
      id: '/_authenticated/affiliate/'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps/create': {
      id: '/_authenticated/vps/create'
      path: '/vps/create'
      fullPath: '/vps/create'
      preLoaderRoute: typeof AuthenticatedVpsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps/$vpsId': {
      id: '/_authenticated/vps/$vpsId'
      path: '/vps/$vpsId'
      fullPath: '/vps/$vpsId'
      preLoaderRoute: typeof AuthenticatedVpsVpsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domain/create': {
      id: '/_authenticated/domain/create'
      path: '/domain/create'
      fullPath: '/domain/create'
      preLoaderRoute: typeof AuthenticatedDomainCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domain/$domainId': {
      id: '/_authenticated/domain/$domainId'
      path: '/domain/$domainId'
      fullPath: '/domain/$domainId'
      preLoaderRoute: typeof AuthenticatedDomainDomainIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database/create': {
      id: '/_authenticated/database/create'
      path: '/database/create'
      fullPath: '/database/create'
      preLoaderRoute: typeof AuthenticatedDatabaseCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database/$databaseId': {
      id: '/_authenticated/database/$databaseId'
      path: '/database/$databaseId'
      fullPath: '/database/$databaseId'
      preLoaderRoute: typeof AuthenticatedDatabaseDatabaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers/create': {
      id: '/_authenticated/containers/create'
      path: '/containers/create'
      fullPath: '/containers/create'
      preLoaderRoute: typeof AuthenticatedContainersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers/$containerId': {
      id: '/_authenticated/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof AuthenticatedContainersContainerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSupportRouteRoute: typeof AuthenticatedSupportRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContainersContainerIdRoute: typeof AuthenticatedContainersContainerIdRoute
  AuthenticatedContainersCreateRoute: typeof AuthenticatedContainersCreateRoute
  AuthenticatedDatabaseDatabaseIdRoute: typeof AuthenticatedDatabaseDatabaseIdRoute
  AuthenticatedDatabaseCreateRoute: typeof AuthenticatedDatabaseCreateRoute
  AuthenticatedDomainDomainIdRoute: typeof AuthenticatedDomainDomainIdRoute
  AuthenticatedDomainCreateRoute: typeof AuthenticatedDomainCreateRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedVpsVpsIdRoute: typeof AuthenticatedVpsVpsIdRoute
  AuthenticatedVpsCreateRoute: typeof AuthenticatedVpsCreateRoute
  AuthenticatedAffiliateIndexRoute: typeof AuthenticatedAffiliateIndexRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedContainersIndexRoute: typeof AuthenticatedContainersIndexRoute
  AuthenticatedDatabaseIndexRoute: typeof AuthenticatedDatabaseIndexRoute
  AuthenticatedDomainIndexRoute: typeof AuthenticatedDomainIndexRoute
  AuthenticatedVpsIndexRoute: typeof AuthenticatedVpsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSupportRouteRoute: AuthenticatedSupportRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContainersContainerIdRoute:
    AuthenticatedContainersContainerIdRoute,
  AuthenticatedContainersCreateRoute: AuthenticatedContainersCreateRoute,
  AuthenticatedDatabaseDatabaseIdRoute: AuthenticatedDatabaseDatabaseIdRoute,
  AuthenticatedDatabaseCreateRoute: AuthenticatedDatabaseCreateRoute,
  AuthenticatedDomainDomainIdRoute: AuthenticatedDomainDomainIdRoute,
  AuthenticatedDomainCreateRoute: AuthenticatedDomainCreateRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedVpsVpsIdRoute: AuthenticatedVpsVpsIdRoute,
  AuthenticatedVpsCreateRoute: AuthenticatedVpsCreateRoute,
  AuthenticatedAffiliateIndexRoute: AuthenticatedAffiliateIndexRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedContainersIndexRoute: AuthenticatedContainersIndexRoute,
  AuthenticatedDatabaseIndexRoute: AuthenticatedDatabaseIndexRoute,
  AuthenticatedDomainIndexRoute: AuthenticatedDomainIndexRoute,
  AuthenticatedVpsIndexRoute: AuthenticatedVpsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
